services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Karachi
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=hamzazahoor1067@gmail.com
      - N8N_BASIC_AUTH_PASSWORD=1234ABcd@
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
